# Generated by Django 4.2 on 2023-04-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_note_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwords',
            field=models.CharField(default='senha', max_length=20),
            preserve_default=False,
        ),
    ]
