# Generated by Django 4.2 on 2023-04-04 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_tipodenota'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.tipodenota'),
        ),
    ]
