# Generated by Django 4.2 on 2023-04-04 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_note_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_title',
            new_name='title',
        ),
    ]
