# Generated by Django 4.2 on 2023-04-04 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_rename_note_title_note_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_text',
            new_name='text',
        ),
    ]
