# Generated by Django 4.2 on 2023-04-04 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_rename_note_text_note_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userr0',
        ),
    ]
