# Generated by Django 4.2 on 2023-04-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_delete_userr0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwords',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=20000),
        ),
    ]
