# Generated by Django 4.2 on 2023-04-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_rename_passwords_user_password_alter_note_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
