# Generated by Django 4.2 on 2023-04-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_note_text_alter_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
